#引入mybatis的配置信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  #    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
